version: '3'
services:

  mongo:
    image: mongo
    restart: always
    env_file:
      - vars.env
    networks:
      - app-tier

  python_app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - vars.env
    depends_on:
      - mongo
    networks:
      - app-tier


networks:
  app-tier:
    driver: bridge